services:
  sqlserver2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Maibok!In0ng'
    ports:
      - '1433:1433'
    volumes:
      - sqlserverdata:/var/opt/mssql
volumes:
  sqlserverdata: